services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - internal_network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - internal_network  

networks:
  internal_network:
    driver: bridge